# SPDX-FileCopyrightText: Copyright (c) 2024–2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-2-Clause

"""BookingAPI — business logic sitting on the SQLite schema.

Single class exposing every operation the voice agent needs.  Reads
come back as plain dicts; mutations run inside explicit transactions
(``with conn:``) so activity_log + confirmation_codes + pnrs updates
either all land or all roll back.

Confirmation codes are 8-character uppercase hex generated by
:mod:`secrets` with a DB-UNIQUE retry loop — not hand-rolled, not
LLM-generated, not deterministic.

FastAPI routes in :mod:`examples.frontend_backend_agent.airline.database.server` forward each call to
this class; an MCP transport can replace FastAPI without touching the
service layer or schema.
"""

from __future__ import annotations

import json
import secrets
import sqlite3
from datetime import UTC, date, datetime, timedelta

from loguru import logger

_CODE_RETRIES = 10


def _now() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat()


def _gen_pnr() -> str:
    """Generate a fresh 6-character PNR (3 uppercase letters + 3 digits)."""
    import random
    import string

    letters = "".join(random.choice(string.ascii_uppercase) for _ in range(3))
    digits = "".join(random.choice(string.digits) for _ in range(3))
    return letters + digits


_MEAL_CODE_LOOKUP = {
    "vegetarian": "VGML",
    "vegan": "VGML",
    "non_vegetarian": "NVML",
    "non-vegetarian": "NVML",
    "nonvegetarian": "NVML",
    "regular": "NVML",
    "kosher": "KSML",
    "halal": "MOML",
    "gluten_free": "GFML",
    "gluten-free": "GFML",
}

# US-registered airports (3-letter IATA) used for the domestic-vs-international
# pricing heuristic.  Cheap stand-in for a real route classifier.
_DOMESTIC_AIRPORTS = frozenset(
    {
        "JFK",
        "LGA",
        "EWR",
        "BOS",
        "ATL",
        "DFW",
        "DCA",
        "IAD",
        "BWI",
        "ORD",
        "MDW",
        "LAX",
        "SFO",
        "SJC",
        "SEA",
        "PDX",
        "DEN",
        "MIA",
        "FLL",
        "PHX",
        "LAS",
        "MSP",
        "IAH",
        "HOU",
        "CLT",
    }
)


def _canonical_meal(meal: str | None) -> str | None:
    """Map free-form caller meal input to a canonical airline meal code."""
    if meal is None:
        return None
    key = meal.strip().lower().replace(" ", "_")
    if not key:
        return None
    return _MEAL_CODE_LOOKUP.get(key, key.upper())


def _materialize_flight_row(
    row: dict,
    travel_date: str,
    *,
    departure_override: str | None = None,
) -> dict:
    """Move a seed flight row onto ``travel_date`` while preserving time/duration."""
    data = dict(row)
    departure = str(data.get("departure") or "")
    arrival = str(data.get("arrival") or departure)
    override_departure = datetime.fromisoformat(departure_override) if departure_override else None
    try:
        departure_dt = datetime.fromisoformat(departure)
        arrival_dt = datetime.fromisoformat(arrival)
        target_date = date.fromisoformat(travel_date)
        materialized_departure = departure_dt.replace(
            year=target_date.year,
            month=target_date.month,
            day=target_date.day,
        )
        if override_departure:
            materialized_departure = override_departure
        duration = arrival_dt - departure_dt
        if duration.total_seconds() < 0:
            duration += timedelta(days=1)
        materialized_arrival = materialized_departure + duration
        data["departure"] = materialized_departure.isoformat()
        data["arrival"] = materialized_arrival.isoformat()
    except ValueError:
        if "T" in departure:
            data["departure"] = f"{travel_date}{departure[10:]}"
        if "T" in arrival:
            data["arrival"] = f"{travel_date}{arrival[10:]}"
    return data


def _unique_daily_flight_rows(rows: list[dict]) -> list[dict]:
    """Keep one schedule template per flight/time for a route."""
    unique: list[dict] = []
    seen: set[tuple[str, str, str, str]] = set()
    for row in rows:
        key = (
            str(row.get("flight_number") or ""),
            str(row.get("origin") or ""),
            str(row.get("destination") or ""),
            str(row.get("departure") or "")[11:],
        )
        if key in seen:
            continue
        seen.add(key)
        unique.append(row)
    return unique


def _select_template_for_time(rows: list[dict], requested_time: str) -> dict:
    """Prefer a template with the same departure time, else use the earliest one."""
    if requested_time:
        for row in rows:
            if str(row.get("departure") or "")[11:] == requested_time:
                return row
    return rows[0]


class BookingAPI:
    """Service-layer API backed by a per-process SQLite connection."""

    def __init__(self, conn: sqlite3.Connection) -> None:
        """Bind to ``conn`` (caller owns the lifecycle)."""
        self._conn = conn

    # ------------------------------------------------------------------
    # Reads
    # ------------------------------------------------------------------

    def get_pnr(self, pnr: str) -> dict | None:
        """Return the booking dict for ``pnr`` (with edit-distance-1 fallback).

        Result mirrors the old ``_backend.get_pnr`` shape:
        ``{pnr, passenger, flight_number, origin, destination, departure,
        cabin, fare_basis, elite_tier, status, delay_minutes, ancillaries}``.
        """
        canonical = pnr.strip().upper()
        row = self._fetch_pnr_row(canonical)
        if row is None:
            fuzzy = self._fuzzy_match_pnr(canonical)
            if fuzzy is None:
                return None
            logger.warning(f"PNR lookup corrected {canonical!r} -> {fuzzy!r} via fuzzy match")
            row = self._fetch_pnr_row(fuzzy)
            if row is None:
                return None
        return self._row_to_booking(row)

    def find_by_flight(self, flight_number: str) -> list[dict]:
        """Return active booking dicts whose current flight matches ``flight_number``.

        Cancelled PNRs are filtered out — they no longer occupy a seat
        on the flight roster.
        """
        fn = flight_number.strip().upper()
        rows = self._conn.execute(
            """
            SELECT p.*, p.status AS booking_status,
                   f.flight_number, f.origin, f.destination, f.departure,
                   f.cabin, f.status AS flight_status, f.delay_minutes,
                   a.seat, a.bag_count, a.meal
            FROM pnrs p
            JOIN flights f ON p.flight_id = f.id
            LEFT JOIN ancillaries a ON a.pnr = p.pnr
            WHERE f.flight_number = ? AND p.status = 'active'
            """,
            (fn,),
        ).fetchall()
        return [self._row_to_booking(r) for r in rows]

    def get_flight_status(self, flight_number: str) -> dict | None:
        """Return live status for ``flight_number`` from the flights table.

        Independent of whether any PNR is booked on the flight — queries
        ``flights`` directly so unbooked / empty-roster flights still
        surface a status to the caller.  ``None`` when the flight
        designator isn't scheduled at all.
        """
        fn = flight_number.strip().upper()
        row = self._conn.execute(
            """
            SELECT flight_number, origin, destination, departure, arrival,
                   cabin, status, delay_minutes
            FROM flights
            WHERE flight_number = ?
            ORDER BY departure ASC
            LIMIT 1
            """,
            (fn,),
        ).fetchone()
        return dict(row) if row is not None else None

    def route_exists(self, origin: str, destination: str) -> bool:
        """Return True when at least one scheduled flight serves the route."""
        row = self._conn.execute(
            "SELECT 1 FROM flights WHERE origin = ? AND destination = ? LIMIT 1",
            (origin.strip().upper(), destination.strip().upper()),
        ).fetchone()
        return row is not None

    def list_alternatives(self, origin: str, destination: str, travel_date: str | None = None) -> list[dict]:
        """Return candidate replacement flights on the given route."""
        origin_u = origin.strip().upper()
        destination_u = destination.strip().upper()
        rows = self._conn.execute(
            """
            SELECT flight_number, origin, destination, departure, arrival, cabin, status, delay_minutes
            FROM flights
            WHERE origin = ? AND destination = ?
            ORDER BY departure ASC
            """,
            (origin_u, destination_u),
        ).fetchall()
        alternatives = [dict(r) for r in rows]
        if not travel_date:
            return alternatives
        return [_materialize_flight_row(row, travel_date) for row in _unique_daily_flight_rows(alternatives)]

    def list_routes(
        self,
        *,
        origin: str | None = None,
        destination: str | None = None,
    ) -> list[dict]:
        """Return scheduled routes grouped by origin/destination.

        Exactly one of ``origin`` / ``destination`` must be supplied.
        - ``origin`` given → rows are (destination, flight_count) for
          all airports reachable from that origin.
        - ``destination`` given → rows are (origin, flight_count) for
          all airports that fly into that destination.

        Empty list when nothing scheduled.  Raises :class:`ValueError`
        on invalid arguments so the handler can return HTTP 400 cleanly.
        """
        if (origin is None) == (destination is None):
            raise ValueError("list_routes requires exactly one of origin or destination")
        if origin is not None:
            origin_u = origin.strip().upper()
            rows = self._conn.execute(
                """
                SELECT destination AS code, COUNT(*) AS flight_count
                FROM flights
                WHERE origin = ?
                GROUP BY destination
                ORDER BY flight_count DESC, destination ASC
                """,
                (origin_u,),
            ).fetchall()
        else:
            destination_u = destination.strip().upper()  # type: ignore[union-attr]
            rows = self._conn.execute(
                """
                SELECT origin AS code, COUNT(*) AS flight_count
                FROM flights
                WHERE destination = ?
                GROUP BY origin
                ORDER BY flight_count DESC, origin ASC
                """,
                (destination_u,),
            ).fetchall()
        return [dict(r) for r in rows]

    def ancillaries_diff(self, pnr: str, new_flight_number: str) -> dict | None:
        """Preview seat / bag / meal carry-over for a proposed rebook.

        Flights ending in ``91`` simulate an equipment swap that forces
        seat reassignment — same heuristic the old backend used so
        orchestrator and DB backends agree on the diff.
        """
        booking = self.get_pnr(pnr)
        if booking is None:
            return None
        new_flight = new_flight_number.strip().upper()
        anc = booking["ancillaries"]
        seat_ok = not new_flight.endswith("91")
        seat_status = "preserved" if seat_ok else "reassigned"
        bag_status = "preserved"
        meal_status = "preserved" if anc["meal"] else "n/a"
        losses: list[str] = []
        if seat_status != "preserved":
            losses.append(f"seat {anc['seat']} → to be reassigned")
        return {
            "pnr": booking["pnr"],
            "new_flight_number": new_flight,
            "seat": {"status": seat_status, "current": anc["seat"]},
            "bags": {"status": bag_status, "count": anc["bag_count"]},
            "meal": {"status": meal_status, "code": anc["meal"]},
            "losses": losses,
        }

    def get_activity(self, pnr: str) -> list[dict]:
        """Return the full activity log for ``pnr``, oldest to newest."""
        canonical = pnr.strip().upper()
        rows = self._conn.execute(
            """
            SELECT * FROM activity_log
            WHERE pnr = ?
            ORDER BY created_at ASC, id ASC
            """,
            (canonical,),
        ).fetchall()
        return [self._activity_row_to_dict(r) for r in rows]

    # ------------------------------------------------------------------
    # Mutations
    # ------------------------------------------------------------------

    def commit_rebook(
        self,
        pnr: str,
        new_flight_number: str,
        session_id: str | None = None,
        seat: str | None = None,
        meal: str | None = None,
        departure: str | None = None,
    ) -> dict | None:
        """Swap ``pnr``'s flight to ``new_flight_number`` and log the event.

        ``seat`` / ``meal`` are optional updates to the ancillaries row;
        any value matching ``"keep"`` / ``"same"`` / the existing stored
        value is treated as a no-op so callers can pass through the
        caller's verbatim preference without writing a duplicate.  The
        update runs in the same transaction as the flight swap so the
        booking never lands partially mutated.
        """
        canonical_pnr = pnr.strip().upper()
        new_flight = new_flight_number.strip().upper()
        with self._conn:
            current = self._fetch_pnr_row(canonical_pnr)
            if current is None:
                return None
            if current["booking_status"] != "active":
                logger.warning(
                    f"commit_rebook refused for {canonical_pnr!r}: "
                    f"booking_status={current['booking_status']!r} (not active)"
                )
                return None
            # When the caller supplies departure, lock to that exact
            # (flight_number, departure) row — same uniqueness key the
            # schema enforces.  Without it, we fall back to "earliest
            # scheduled" which is unsafe when flight numbers recur
            # across dates / routes.
            if departure:
                new_flight_row = self._conn.execute(
                    "SELECT id, flight_number, origin, destination, departure FROM flights "
                    "WHERE flight_number = ? AND departure = ? LIMIT 1",
                    (new_flight, departure),
                ).fetchone()
            else:
                new_flight_row = self._conn.execute(
                    "SELECT id, flight_number, origin, destination, departure FROM flights "
                    "WHERE flight_number = ? ORDER BY departure ASC LIMIT 1",
                    (new_flight,),
                ).fetchone()
            if new_flight_row is None:
                return None
            self._conn.execute(
                "UPDATE pnrs SET flight_id = ?, updated_at = ? WHERE pnr = ?",
                (new_flight_row["id"], _now(), canonical_pnr),
            )
            self._apply_ancillary_updates(canonical_pnr, seat=seat, meal=meal)
            code = self._issue_code(canonical_pnr, "REBOOK")
            self._log_activity(
                pnr=canonical_pnr,
                action="REBOOK",
                session_id=session_id,
                from_flight=current["flight_number"],
                from_origin=current["origin"],
                from_destination=current["destination"],
                from_departure=current["departure"],
                to_flight=new_flight_row["flight_number"],
                to_origin=new_flight_row["origin"],
                to_destination=new_flight_row["destination"],
                to_departure=new_flight_row["departure"],
                outcome="committed",
                confirmation_code=code,
            )
        booking = self.get_pnr(canonical_pnr)
        return {
            "booking": booking,
            "confirmation_code": code,
            "from_flight": current["flight_number"],
            "to_flight": new_flight_row["flight_number"],
            "new_flight_number": new_flight_row["flight_number"],
        }

    _KEEP_TOKENS = frozenset({"keep", "same", "no_change", "existing", "unchanged"})

    _MEAL_CODE_MAP = {
        "vegetarian": "VGML",
        "vegan": "VGML",
        "non_vegetarian": "NVML",
        "non-vegetarian": "NVML",
        "nonvegetarian": "NVML",
        "regular": "NVML",
        "kosher": "KSML",
        "halal": "MOML",
        "gluten_free": "GFML",
        "gluten-free": "GFML",
    }

    def _apply_ancillary_updates(
        self,
        pnr: str,
        *,
        seat: str | None,
        meal: str | None,
    ) -> None:
        """Apply seat / meal changes to the ancillaries row, skipping no-ops.

        Canonicalises free-form caller phrasing ('non-vegetarian' → 'NVML',
        'keep' → skip) so downstream reads see stable codes.  Runs inside
        the caller's existing transaction (the commit method wraps us in
        ``with self._conn``).
        """
        if seat is None and meal is None:
            return
        row = self._conn.execute(
            "SELECT seat, meal FROM ancillaries WHERE pnr = ?",
            (pnr,),
        ).fetchone()
        if row is None:
            return
        new_seat = row["seat"]
        new_meal = row["meal"]
        if seat is not None:
            seat_clean = seat.strip()
            if seat_clean.lower() not in self._KEEP_TOKENS and seat_clean:
                new_seat = seat_clean.upper()
        if meal is not None:
            meal_clean = meal.strip().lower().replace(" ", "_")
            if meal_clean not in self._KEEP_TOKENS and meal_clean:
                new_meal = self._MEAL_CODE_MAP.get(meal_clean, meal_clean.upper())
        if new_seat == row["seat"] and new_meal == row["meal"]:
            return
        self._conn.execute(
            "UPDATE ancillaries SET seat = ?, meal = ? WHERE pnr = ?",
            (new_seat, new_meal, pnr),
        )

    def cancel_booking(
        self,
        pnr: str,
        kind: str,
        policy_ref: str,
        session_id: str | None = None,
    ) -> dict | None:
        """Mark ``pnr`` as cancelled, log the event, and return a code.

        ``kind`` is a short classifier string (airline_refund,
        voluntary_refundable, voluntary_basic, ...) carried into the
        activity log's ``outcome`` for audit.
        """
        canonical = pnr.strip().upper()
        with self._conn:
            current = self._fetch_pnr_row(canonical)
            if current is None:
                return None
            if current["booking_status"] != "active":
                logger.warning(
                    f"cancel_booking refused for {canonical!r}: "
                    f"booking_status={current['booking_status']!r} (already cancelled)"
                )
                return None
            self._conn.execute(
                "UPDATE pnrs SET status = 'cancelled', updated_at = ? WHERE pnr = ?",
                (_now(), canonical),
            )
            code = self._issue_code(canonical, "CANCEL")
            self._log_activity(
                pnr=canonical,
                action="CANCEL",
                session_id=session_id,
                from_flight=current["flight_number"],
                from_origin=current["origin"],
                from_destination=current["destination"],
                from_departure=current["departure"],
                outcome=kind,
                policy_ref=policy_ref,
                confirmation_code=code,
            )
        return {"confirmation_code": code, "pnr": canonical, "kind": kind}

    _CABIN_PRICE = {
        "economy": 150.0,
        "premium_economy": 275.0,
        "business": 600.0,
        "first": 1200.0,
    }

    @staticmethod
    def _domestic_route(origin: str, destination: str) -> bool:
        """Return ``True`` when both airports are in the US-domestic set."""
        return origin.upper() in _DOMESTIC_AIRPORTS and destination.upper() in _DOMESTIC_AIRPORTS

    def price_for(self, origin: str, destination: str, cabin: str) -> str:
        """Return a human-readable fare estimate for a new booking.

        Flat rate per cabin with a 2x international surcharge.  Not a
        real revenue-management model — just enough to give the caller
        a concrete number before they confirm.
        """
        base = self._CABIN_PRICE.get(cabin.lower(), self._CABIN_PRICE["economy"])
        if not self._domestic_route(origin, destination):
            base *= 2.0
        return f"{base:.2f}"

    def create_booking(
        self,
        passenger: str,
        origin: str,
        destination: str,
        flight_number: str,
        departure: str | None = None,
        seat: str | None = None,
        meal: str | None = None,
        cabin: str | None = None,
        fare_basis: str = "nonrefundable",
        session_id: str | None = None,
    ) -> dict | None:
        """Create a brand-new PNR on ``flight_number`` for ``passenger``.

        Generates a fresh 6-character PNR (3 letters + 3 digits) and
        inserts matching rows into ``pnrs`` and ``ancillaries``.  The
        booked cabin is always the FLIGHT's scheduled cabin — the
        caller-supplied ``cabin`` argument is treated as a hint and a
        mismatch is logged but does not override.  This keeps the
        receipt and the durable record in agreement; cabin selection
        belongs at flight-pick time, not at booking time.
        """
        origin_u = origin.strip().upper()
        destination_u = destination.strip().upper()
        flight_u = flight_number.strip().upper()
        with self._conn:
            flight_row = self._find_or_create_flight_row(
                flight_number=flight_u,
                origin=origin_u,
                destination=destination_u,
                departure=departure,
            )
            if flight_row is None:
                return None
            if cabin and cabin.strip().lower() != (flight_row["cabin"] or "").lower():
                logger.warning(
                    f"create_booking ignoring cabin hint {cabin!r} for {flight_u}: "
                    f"flight is scheduled in {flight_row['cabin']!r}"
                )
            # Retry a few times on the (unlikely) PNR collision so we
            # don't surface the user-visible IntegrityError.
            new_pnr = None
            for _ in range(8):
                candidate = _gen_pnr()
                exists = self._conn.execute(
                    "SELECT 1 FROM pnrs WHERE pnr = ?",
                    (candidate,),
                ).fetchone()
                if exists is None:
                    new_pnr = candidate
                    break
            if new_pnr is None:
                return None
            ts = _now()
            self._conn.execute(
                """
                INSERT INTO pnrs (pnr, passenger, flight_id, fare_basis, elite_tier, status, created_at, updated_at)
                VALUES (?, ?, ?, ?, 'none', 'active', ?, ?)
                """,
                (new_pnr, passenger.strip() or "Guest", flight_row["id"], fare_basis, ts, ts),
            )
            self._conn.execute(
                "INSERT INTO ancillaries (pnr, seat, bag_count, meal) VALUES (?, ?, ?, ?)",
                (new_pnr, (seat or "").strip().upper() or None, 0, _canonical_meal(meal)),
            )
            effective_cabin = (flight_row["cabin"] or "economy").lower()
            price = self.price_for(flight_row["origin"], flight_row["destination"], effective_cabin)
            code = self._issue_code(new_pnr, "BOOK")
            self._log_activity(
                pnr=new_pnr,
                action="BOOK",
                session_id=session_id,
                to_flight=flight_row["flight_number"],
                to_origin=flight_row["origin"],
                to_destination=flight_row["destination"],
                to_departure=flight_row["departure"],
                outcome="booked",
                confirmation_code=code,
            )
        return {
            "pnr": new_pnr,
            "confirmation_code": code,
            "flight_number": flight_row["flight_number"],
            "origin": flight_row["origin"],
            "destination": flight_row["destination"],
            "departure": flight_row["departure"],
            "cabin": effective_cabin,
            "fare_basis": fare_basis,
            "price": price,
            "currency": "USD",
        }

    def list_standby(
        self,
        pnr: str,
        standby_flight_number: str,
        session_id: str | None = None,
        departure: str | None = None,
    ) -> dict | None:
        """Queue ``pnr`` for standby on ``standby_flight_number``.

        Unlike rebook, standby doesn't mutate the PNR's flight — the
        caller keeps their ticket and is listed for an earlier
        departure.  We just log and mint a tracking code.
        """
        canonical = pnr.strip().upper()
        standby_flight = standby_flight_number.strip().upper()
        with self._conn:
            current = self._fetch_pnr_row(canonical)
            if current is None:
                return None
            if current["booking_status"] != "active":
                logger.warning(
                    f"list_standby refused for {canonical!r}: booking_status={current['booking_status']!r} (not active)"
                )
                return None
            if departure:
                standby_row = self._conn.execute(
                    "SELECT flight_number, origin, destination, departure FROM flights "
                    "WHERE flight_number = ? AND departure = ? LIMIT 1",
                    (standby_flight, departure),
                ).fetchone()
            else:
                standby_row = self._conn.execute(
                    "SELECT flight_number, origin, destination, departure FROM flights "
                    "WHERE flight_number = ? ORDER BY departure ASC LIMIT 1",
                    (standby_flight,),
                ).fetchone()
            if standby_row is None:
                return None
            code = self._issue_code(canonical, "STANDBY")
            self._log_activity(
                pnr=canonical,
                action="STANDBY",
                session_id=session_id,
                from_flight=current["flight_number"],
                from_origin=current["origin"],
                from_destination=current["destination"],
                from_departure=current["departure"],
                to_flight=standby_row["flight_number"],
                to_origin=standby_row["origin"],
                to_destination=standby_row["destination"],
                to_departure=standby_row["departure"],
                outcome="listed",
                confirmation_code=code,
            )
        return {
            "confirmation_code": code,
            "pnr": canonical,
            "standby_flight": standby_flight,
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _find_or_create_flight_row(
        self,
        *,
        flight_number: str,
        origin: str,
        destination: str,
        departure: str | None,
    ) -> sqlite3.Row | None:
        if not departure:
            return self._conn.execute(
                """
                SELECT id, flight_number, origin, destination, departure, arrival, cabin
                FROM flights
                WHERE flight_number = ? AND origin = ? AND destination = ?
                ORDER BY departure ASC
                LIMIT 1
                """,
                (flight_number, origin, destination),
            ).fetchone()

        exact = self._conn.execute(
            """
            SELECT id, flight_number, origin, destination, departure, arrival, cabin
            FROM flights
            WHERE flight_number = ? AND origin = ? AND destination = ? AND departure = ?
            LIMIT 1
            """,
            (flight_number, origin, destination, departure),
        ).fetchone()
        if exact is not None:
            return exact

        requested_time = departure[11:] if len(departure) > 11 else ""
        rows = self._conn.execute(
            """
            SELECT flight_number, origin, destination, departure, arrival, cabin, status, delay_minutes
            FROM flights
            WHERE flight_number = ? AND origin = ? AND destination = ?
            ORDER BY departure ASC
            """,
            (flight_number, origin, destination),
        ).fetchall()
        if not rows:
            return None

        template = _select_template_for_time([dict(row) for row in rows], requested_time)
        materialized = _materialize_flight_row(template, departure[:10], departure_override=departure)
        self._conn.execute(
            """
            INSERT OR IGNORE INTO flights
            (flight_number, origin, destination, departure, arrival, cabin, status, delay_minutes)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                materialized["flight_number"],
                materialized["origin"],
                materialized["destination"],
                materialized["departure"],
                materialized["arrival"],
                materialized["cabin"],
                materialized.get("status") or "scheduled",
                int(materialized.get("delay_minutes") or 0),
            ),
        )
        return self._conn.execute(
            """
            SELECT id, flight_number, origin, destination, departure, arrival, cabin
            FROM flights
            WHERE flight_number = ? AND origin = ? AND destination = ? AND departure = ?
            LIMIT 1
            """,
            (flight_number, origin, destination, materialized["departure"]),
        ).fetchone()

    def _fetch_pnr_row(self, pnr: str) -> sqlite3.Row | None:
        return self._conn.execute(
            """
            SELECT p.pnr, p.passenger, p.fare_basis, p.elite_tier,
                   p.status AS booking_status,
                   f.flight_number, f.origin, f.destination, f.departure,
                   f.cabin, f.status AS flight_status, f.delay_minutes,
                   a.seat, a.bag_count, a.meal
            FROM pnrs p
            JOIN flights f ON p.flight_id = f.id
            LEFT JOIN ancillaries a ON a.pnr = p.pnr
            WHERE p.pnr = ?
            """,
            (pnr,),
        ).fetchone()

    def _fuzzy_match_pnr(self, pnr: str, max_distance: int = 1) -> str | None:
        """Edit-distance-1 fuzzy match against all known PNRs. None on tie."""
        rows = self._conn.execute("SELECT pnr FROM pnrs").fetchall()
        best: tuple[int, str] | None = None
        tie = False
        for row in rows:
            d = _edit_distance(pnr, row["pnr"])
            if d > max_distance:
                continue
            if best is None or d < best[0]:
                best = (d, row["pnr"])
                tie = False
            elif d == best[0]:
                tie = True
        if best is None or tie:
            return None
        return best[1]

    def _row_to_booking(self, row: sqlite3.Row) -> dict:
        """Shape a joined flights/pnrs/ancillaries row as a booking dict.

        ``status`` is the FLIGHT operational status (scheduled/delayed/...)
        and ``booking_status`` is the PNR lifecycle (active/cancelled);
        callers must check ``booking_status`` before treating a record as
        operable — a cancelled PNR can still join an on-time flight row.
        """
        return {
            "pnr": row["pnr"],
            "passenger": row["passenger"],
            "flight_number": row["flight_number"],
            "origin": row["origin"],
            "destination": row["destination"],
            "departure": row["departure"],
            "cabin": row["cabin"],
            "fare_basis": row["fare_basis"],
            "elite_tier": row["elite_tier"],
            "status": row["flight_status"],
            "booking_status": row["booking_status"],
            "delay_minutes": row["delay_minutes"],
            "ancillaries": {
                "seat": row["seat"],
                "bag_count": row["bag_count"] or 0,
                "meal": row["meal"],
            },
        }

    @staticmethod
    def _activity_row_to_dict(row: sqlite3.Row) -> dict:
        data = dict(row)
        amounts_json = data.pop("amounts_json", None)
        if amounts_json:
            try:
                data["amounts"] = json.loads(amounts_json)
            except json.JSONDecodeError:
                data["amounts"] = None
        return data

    def _issue_code(self, pnr: str, action: str) -> str:
        """Mint a unique 8-char code, retrying on astronomically rare collisions."""
        for _ in range(_CODE_RETRIES):
            code = secrets.token_hex(4).upper()
            try:
                self._conn.execute(
                    "INSERT INTO confirmation_codes (code, pnr, action, issued_at) VALUES (?, ?, ?, ?)",
                    (code, pnr, action, _now()),
                )
                return code
            except sqlite3.IntegrityError:
                continue
        raise RuntimeError(f"confirmation code collision retry exhausted for {action}/{pnr}")

    def _log_activity(self, **fields) -> None:
        """Insert a row into activity_log. ``pnr`` and ``action`` required.

        Only non-None keys are written, so callers pass exactly the
        columns that apply (e.g. cancel omits ``to_*``).  Column list
        is built from the kwargs dict; Python 3.7+ preserves insertion
        order so the parallel ``values`` list matches position-wise.
        """
        fields.setdefault("created_at", _now())
        columns = [k for k in fields if fields[k] is not None]
        values = [fields[k] for k in columns]
        placeholders = ", ".join("?" * len(columns))
        self._conn.execute(
            f"INSERT INTO activity_log ({', '.join(columns)}) VALUES ({placeholders})",
            values,
        )


def _edit_distance(a: str, b: str) -> int:
    """Levenshtein distance. Small strings only — quadratic in length."""
    if a == b:
        return 0
    la, lb = len(a), len(b)
    if abs(la - lb) > 2:
        return max(la, lb)
    prev = list(range(lb + 1))
    for i, ca in enumerate(a, start=1):
        row = [i]
        for j, cb in enumerate(b, start=1):
            cost = 0 if ca == cb else 1
            row.append(min(row[-1] + 1, prev[j] + 1, prev[j - 1] + cost))
        prev = row
    return prev[-1]
