# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Financial CLM (Causal Language Modeling) Dataset for decoder-only pretraining.

Reads text corpus lines generated by the tokenizer pipeline and produces
(input_ids, labels) pairs for next-token prediction. No masking logic is
needed -- every token position provides a training signal.

Corpus line format:
    <bos> AMT_3 MERCH_1498 ... <sep> AMT_1 MERCH_42 ... <eos>

For causal LM:
    input_ids = full token sequence
    labels    = same as input_ids, with <pad> positions set to -100
                (HuggingFace convention: -100 = ignore in loss)

The model's forward pass handles the internal shift: it predicts
position i+1 from position i.

NeMo AutoModel Integration
--------------------------
Referenced in YAML via file-path:function ``_target_`` syntax::

    dataset:
      _target_: src/clm_data.py:build_financial_clm_dataset
      data_path: /path/to/train_corpus.txt
      seq_length: 4096

NeMo AutoModel resolves the ``_target_``, calls ``build_financial_clm_dataset()``
with the remaining keys as kwargs, and wraps the returned Dataset in a
``StatefulDataLoader``.
"""

import sys
from pathlib import Path
from typing import Dict, List, Union

import numpy as np
import torch
from torch.utils.data import Dataset

# Ensure tokenizer subpackage is importable when loaded by NeMo's
# file-path _target_ resolution (which bypasses normal package imports).
_src_dir = str(Path(__file__).resolve().parent)
if _src_dir not in sys.path:
    sys.path.insert(0, _src_dir)


class FinancialCLMDataset(Dataset):
    """PyTorch Dataset for causal language modeling on financial transactions.

    Compatible with NeMo AutoModel's ``StatefulDataLoader`` — returns dicts
    with ``input_ids`` and ``labels`` tensors, matching the interface expected
    by ``MaskedCrossEntropy`` loss and HuggingFace causal LM forward().
    """

    def __init__(
        self,
        sequences: List[List[int]],
        seq_length: int = 4096,
        pad_token_id: int = 0,
    ):
        self.sequences = sequences
        self.seq_length = seq_length
        self.pad_token_id = pad_token_id

    def __len__(self) -> int:
        return len(self.sequences)

    def __getitem__(self, idx: int) -> Dict[str, torch.Tensor]:
        tokens = self.sequences[idx]

        if len(tokens) > self.seq_length:
            tokens = tokens[: self.seq_length]

        input_ids = np.full(self.seq_length, self.pad_token_id, dtype=np.int64)
        input_ids[: len(tokens)] = tokens

        labels = np.full(self.seq_length, -100, dtype=np.int64)
        labels[: len(tokens)] = tokens

        return {
            "input_ids": torch.from_numpy(input_ids),
            "labels": torch.from_numpy(labels),
        }


def load_corpus_and_tokenize(
    data_path: Union[str, Path],
    merchant_hash_size: int = 2000,
    seq_length: int = 4096,
) -> FinancialCLMDataset:
    """Load a text corpus file and build a FinancialCLMDataset.

    Each line in the corpus is a space-separated token string like:
        <bos> AMT_3 MERCH_1498 CAT_RETAIL ... <sep> AMT_1 ... <eos>
    """
    from tokenizer.financial_tokenizer import FinancialTabularTokenizer

    tokenizer = FinancialTabularTokenizer(
        merchant_hash_size=merchant_hash_size,
        category_hierarchy=True,
        temporal_encoding=True,
    )

    data_path = Path(data_path)
    print(f"Loading corpus from {data_path}...")

    sequences = []
    with open(data_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            token_ids = tokenizer.encode(line, max_length=seq_length)
            sequences.append(token_ids)

    print(f"  Loaded {len(sequences):,} sequences (seq_length={seq_length})")

    return FinancialCLMDataset(
        sequences=sequences,
        seq_length=seq_length,
        pad_token_id=tokenizer.pad_token_id,
    )


def build_financial_clm_dataset(
    data_path: str,
    merchant_hash_size: int = 2000,
    seq_length: int = 4096,
    **kwargs,
) -> FinancialCLMDataset:
    """Entry point for NeMo AutoModel YAML config.

    This function is called by the recipe when it resolves the dataset
    ``_target_``. Any extra keys in the YAML dataset section are passed
    as ``**kwargs`` and silently ignored, ensuring forward compatibility
    with new config keys.
    """
    return load_corpus_and_tokenize(
        data_path=data_path,
        merchant_hash_size=merchant_hash_size,
        seq_length=seq_length,
    )
